Repository zinka22/Selenium-cource, pull requests merged in 2024-06, with the labels that each got.

#26 Перенос файла с заданием: fill the form with x path
  README.md
  solutions/fill_the_form_with_XPath.py
  tasks/fill_the_form_with_XPath.md
Labels: documentation

#14 Оформление теста в стиле unittest
  README.md
  solutions/unittest_style.py
  tasks/unittest_style.md
Labels: exercise

#28 Перенос файла с заданием: fill the huge form
  README.md
  fill_the_huge_form.py
  solutions/fill_the_huge_form.py
  tasks/fill_the_huge_form.md
Labels: documentation

#29 Перенос файла с заданием: execute script scroll
  README.md
  solutions/execute_script_scroll.py
  tasks/execute_script_scroll.md
Labels: documentation

#31 Перенос дополнительной логики в функцию get_math_function_value, helpers.py
  get_attribute.py
  helpers.py
  radio_and_checkbox.py
  solutions/confirm_alert.py
  solutions/execute_script_scroll.py
  solutions/expected_conditions.py
  solutions/switch_to_window.py
Labels: refactoring

#32 Единый вид адреса учебного сайта: решение задачи
  check_registration_form.py
  check_registration_with_bugz.py
  get_attribute.py
  helpers.py
  radio_and_checkbox.py
  solutions/confirm_alert.py
  solutions/execute_script_scroll.py
  solutions/expected_conditions.py
  solutions/fill_the_form_with_XPath.py
  solutions/fill_the_huge_form.py
  solutions/switch_to_window.py
  solutions/working_with_dropdown_list.py
  tasks/confirm_alert.md
  tasks/expected_conditions.md
  tasks/fill_the_form_with_XPath.md
  tasks/fill_the_huge_form.md
  tasks/switch_to_window.md
  tasks/unittest_style.md
  upload_file_from_pc/upload_file_from_pc.py
Labels: invalid

#33 Перенос файла с заданием: check registration form
  README.md
  solutions/check_registration_form.py
  tasks/check_registration_form.md
  tasks/fill_the_form_with_XPath.md
  tasks/pytest_style.md
  tasks/unittest_style.md
Labels: documentation

#36 Перенос файла с заданием: get attribute
  README.md
  solutions/get_attribute.py
  tasks/get_attribute.md
Labels: documentation

#37 Перенос файла с заданием: radio and checkbox
  README.md
  solutions/radio_and_checkbox.py
  tasks/execute_script_scroll.md
  tasks/radio_and_checkbox.md
Labels: documentation

#38 Перенос файла с заданием: upload file from pc
  README.md
  solutions/upload_file_from_pc/test__file_for_uploading.txt
  solutions/upload_file_from_pc/upload_file_from_pc.py
  tasks/upload_file_from_pc.md
Labels: documentation

#39 Задача: авторизация на сайте с использованием pytest (test_authorization)
  .gitignore
  README.md
  solutions/pytest_folder/auth_keys_stepik.json
  solutions/pytest_folder/conftest.py
  solutions/pytest_folder/test_authorization.py
  tasks/test_authorization.md
Labels: exercise

#42 Использование pathlib при работе с файлами: upload_file_from_pc
  solutions/upload_file_from_pc/upload_file_from_pc.py
Labels: refactoring, very quick

#41 Задача: параметризация тестов (task_parametrization)
  README.md
  helpers.py
  solutions/pytest_folder/conftest.py
  solutions/pytest_folder/test_parametrization.py
  tasks/test_parametrization.md
Labels: exercise

#45 Единый вид docstrings в helpers.py
  helpers.py
Labels: refactoring

#46 Login verification improvement
  helpers.py
  solutions/pytest_folder/test_authorization.py
  solutions/pytest_folder/test_parametrization.py
Labels: refactoring
