Repository zinka22/Selenium-cource, pull requests merged in 2024-07, with the labels that each got.

#47 Задача: Запуск автотестов для разных языков интерфейса(task_run_for_different_locals)
  README.md
  solutions/pytest_folder/conftest.py
  solutions/pytest_folder/test_run_for_different_locals.py
  tasks/test_run_for_different_locals.md
Labels: exercise

#49 Сортировка функций в conftest по алфавиту(issue_conftest_functions_sort)
  solutions/pytest_folder/conftest.py
Labels: refactoring

#51 test_main_page.md updated
  tasks/test_main_page.md
Labels: documentation, refactoring, exercise

#50 Задание: добавление в корзину со страницы товара (task_add_to_cart)
  README.md
  solutions/page_object/ __init__.py
  solutions/page_object/conftest.py
  solutions/page_object/pages/__init__.py
  solutions/page_object/pages/base_page.py
  solutions/page_object/pages/locators.py
  solutions/page_object/pages/login_page.py
  solutions/page_object/pages/main_page.py
  solutions/page_object/pages/product_page.py
  solutions/page_object/test_main_page.py
  solutions/page_object/test_product_page.py
  tasks/test_main_page.md
  tasks/test_product_page.md
Labels: exercise
